name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  swipeable_button_view: ^0.0.2
  page_transition: ^2.1.0
  bloc: ^8.1.3
  share: ^2.0.4
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: cambo
      fonts:
        - asset: fonts/Cambo/Cambo-Regular.ttf
    - family: lobster
      fonts:
        - asset: fonts/Lobster/Lobster-Regular.ttf
